### ISSUE TITLE
Naiva Question: 

### ISSUE THREAD

**Issue by csv610** [SonicWarrior1/pdfchat#1]
Hello,

I have installed Ollama on my machine. But do not know how to solve the problem. Can you help?

ValueError: Ollama call failed with status code 404. Details: model 'mistral:instruct' not found, try pulling it first

**Comment by SonicWarrior1** [comment]
> Hello,
> 
> I have installed Ollama on my machine. But do not know how to solve the problem. Can you help?
> 
> ValueError: Ollama call failed with status code 404. Details: model 'mistral:instruct' not found, try pulling it first

The error is coming because you haven't pulled/downloaded the Mistral 7b model on to your Local Machine.
If u have installed ollama in docker just like i did then just run this command in cmd and make sure the docker container is running 

`docker exec -it ollama ollama run mistral:instruct`

For the first time this command will download the mistral 7b model and then run it.
After this u can just close the cmd window and try running the code again
