### ISSUE TITLE
I walked through the guideline and got this error.

### ISSUE THREAD

**Issue by ChuBL** [SonicWarrior1/pdfchat#5]
ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs']) Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface. Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

OS: macOS Sonoma 14.3.1
ollama version is 0.1.27
mistral:latest         	61e88e884507	4.1 GB

**Comment by holytony** [comment]
same MacOS, got the same error

**Comment by SonicWarrior1** [comment]
Due to changes in ChromaDb it is incompatible with the langchain version used in this project. But its seems to be fixed in the latest versions, so u should try updating the dependencies and refer to this [issue](https://github.com/langchain-ai/langchain/issues/13061) for more information.

I will be update the repo code in few days with updated dependencies.

**Comment by ChuBL** [comment]
Thank you! Updating langchain makes my day!
